startServer:
	./assignment3 -l 12345 -p "basic"

sendA:
	nc localhost 12345 -d 1 < input/Book_A.txt

sendB:
	nc localhost 12345 -d 1 < input/Book_B.txt

sendC:
	nc localhost 12345 -d 1 < input/Book_C.txt

sendD:
	nc localhost 12345 -d 1 < input/Book_D.txt

sendE:
	nc localhost 12345 -d 1 < input/Book_E.txt

sendF:
	nc localhost 12345 -d 1 < input/Book_F.txt

sendG:
	nc localhost 12345 -d 1 < input/Book_G.txt

sendH:
	nc localhost 12345 -d 1 < input/Book_H.txt

sendI:
	nc localhost 12345 -d 1 < input/Book_I.txt
	
sendJ:
	nc localhost 12345 -d 1 < input/Book_J.txt

sendK:
	nc localhost 12345 -d 1 < input/Book_K.txt

clean:
	rm ./*.txt